resource "helm_release" "keycloak" {
    depends_on = [
        helm_release.kafka
    ]
    repository = "oci://registry-1.docker.io/bitnamicharts"
    name = "keycloak"
    chart = "keycloak"
    version = "22.1.3"
    namespace  = "keycloak"
    create_namespace = true
    set {
        name = "auth.adminUser"
        value = "admin"
    }
    set {
        name = "auth.adminPassword"
        value = "admin"
    }
    set {
        name = "readinessProbe.enabled"
        value = true
    }
    set {
        name = "tls.enabled"
        value = true
    }
    set {
        name = "tls.autoGenerated"
        value = true
    }
}