name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Output Run Id
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push 1
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: true
        with:
          platforms: linux/amd64,linux/arm64
          context: smart-home-monolith
          push: true
          tags: |
            ghcr.io/d-dmitriev/architecture-sprint-3/monolith:latest
            ghcr.io/d-dmitriev/architecture-sprint-3/monolith:0.1.${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push 2
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: true
        with:
          platforms: linux/amd64,linux/arm64
          context: smart-home-telemetry
          push: true
          tags: |
            ghcr.io/d-dmitriev/architecture-sprint-3/telemetry:latest
            ghcr.io/d-dmitriev/architecture-sprint-3/telemetry:0.1.${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Update verison
        run: |
           find . -type f -name "Chart.yaml" -print0 | xargs -0 sed -i "s/appVersion: \"*.*.*\"/appVersion: \"0.1.${{ github.run_number }}\"/g"
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "[skip ci]"
          commit_message: Update app version to 0.1.${{ github.run_number }}
          force: false